[package]
name = "uwp_helper"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "url_launcher"
path = "src/bin/url_launcher.rs"

[[bin]]
name = "get_appdata_folder"
path = "src/bin/get_appdata_folder.rs"

[dependencies.clap]
version = "4"
features = ["derive"]

[dependencies.windows]
version = "0.48.0"
features = ["System", "Foundation", "Storage"]

[dependencies.tokio]
version = "1.25.0"
features = ["macros", "rt-multi-thread"]
