[package]
name = "uwp_helper"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
lazy_static = "1.4.0"

[dependencies.windows]
version = "0.48.0"
features = ["System", "Foundation", "Storage", "Win32_Foundation"]

[dependencies.tokio]
version = "1.29.1"
features = ["macros", "rt-multi-thread"]
