package dev.schlaubi.tonbrett.app.strings

data class Strings(
    val reload: String,
    val crashedExplainer: String,
    val botOfflineExplainer: String,
    val wrongChannelExplainer: String,
    val noSounds: String,
    val offline: String,
    val sessionExpiredExplainer: String,
    val reAuthorize: String,
    val searchExplainer: String,
    val search: String,
    val onlineMine: String,
    val searchByTag: String,
    val searchByName: String,
    val searchByDescription: String,
    val searchOptions: String,
    val enterToAdd: String,
    val loginSuccessful: String,
    val logo: String,
    val loginSuccessfulDescription: String,
    val cliLoginExplainer: String,
    val starOnGithub: String,
    val update: String,
    val appCrash: String,
    val needsUpdate: String,
    val unknownError: String,
    val copyUrl: String
)
