name: Maven CI

on:
  push:
#    tags:
#      - '**'

permissions:
  id-token: write

jobs:
  publish:
    name: Publish To Maven
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 19
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/576023676253/locations/global/workloadIdentityPools/gh-actions'
          service_account: 'gh-actions@mik-music.iam.gserviceaccount.com'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - run: gcloud auth list --filter=status:ACTIVE --format="value(account)"
      - name: Build plugin
        uses: gradle/gradle-build-action@v2
        env:
          JFROG_USER: ${{ secrets.JFROG_USER }}
          JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
          SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
        with:
          arguments: publish
