name: Maven CI

on:
  push:
    tags:
      - '**'

permissions:
  id-token: write

jobs:
  publish:
    name: Publish To Maven
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew publish
        env:
          SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
          GOOGLE_KEY: ${{ secrets.GOOGLE_KEY }}
